services:
  netdata:
    image: netdata/netdata:latest
    container_name: netdata
    restart: always
    pid: "host"
    ports:
      - "19999:19999"
    environment:
      - PGID=998 
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - global_monitoring_net

networks:
  global_monitoring_net:
    external: true
    name: global_monitoring_net

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:

