---
- name: "Deploy Monitoring (Netdata)"
  hosts: ubuntu_server
  vars:
    # Gdzie na Ubuntu ma wylądować projekt
    project_path: "/home/{{ ansible_user }}/projects/monitoring"
    # Adres Twojego nowego repozytorium
    repo_url: "git@github.com:mariuszhoxton/monitoring-project.git"

  tasks:
    - name: "1. Tworzenie folderu projektu na Ubuntu"
      file:
        path: "{{ project_path }}"
        state: directory

    - name: "2. Pobieranie kodu monitoringu z GitHuba na Ubuntu"
      git:
        repo: "{{ repo_url }}"
        dest: "{{ project_path }}"
        version: main
        force: yes

    - name: "3. Uruchomienie Netdata przez Docker Compose"
      community.docker.docker_compose_v2:
        project_src: "{{ project_path }}"
        state: present
